version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-serverless-chaos-engineering-fis"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hmme9geilvz0"
s3_prefix = "aws-serverless-chaos-engineering-fis"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
