AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-serverless-chaos-engineering-fis

  Sample SAM Template for aws-serverless-chaos-engineering-fis

Globals:
  Function:
    Timeout: 3

Resources:
  ChaosLambdaFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: chaos_lambda/
      Handler: app.handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          CHAOS_PARAM: !Ref ServerlessFaultParameter
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello
            Method: get
      Policies:
        - Statement:
          - Sid: SSMDescribeParametersPolicy
            Effect: Allow
            Action:
            - ssm:DescribeParameters
            Resource: '*'
          - Sid: SSMGetParameterPolicy
            Effect: Allow
            Action:
            - ssm:GetParameters
            - ssm:GetParameter
            Resource: '*'

  # SSM Parameter used by chaos-lambda to control failures
  ServerlessFaultParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 'ChaosLambdaParameter'
      Description: 'Parameter controlling failures in chaos-lambda'
      Type: String
      # https://aws-lambda-chaos-injection.readthedocs.io/en/latest/
      # fault-type: one of: latency, status_code, exception
      Value: '{"is_enabled":false,"fault_type":"latency","delay":400,"error_code":404,"exception_msg":"Fault injected by chaos-lambda","rate":1}'

Outputs:
  ChaosLambdaApi:
    Description: "API Gateway endpoint URL for Prod stage for Chaos Lambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ChaosLambdaFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ChaosLambdaFunction.Arn
  ChaosLambdaFunctionRole:
    Description: "Implicit IAM Role created for Chaos Lambda function"
    Value: !GetAtt ChaosLambdaFunctionRole.Arn
